spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${MONGODB_URL}

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
      docExpansion: none

  output:
    ansi:
      enabled: always

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 1209600000

management:
  health:
    mongo:
      enabled: false # TODO: MongoDB Health Check 비활성화, 추후 활성화 필요

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always # nginx에서 ip 제한 처리
    info:
      access: read_only
    prometheus:
      access: read_only
    metrics:
      access: read_only

  metrics:
    tags:
      application: ${spring.application.name}
      version: '@project.version@'
  prometheus:
    metrics:
      export:
        enabled: true
        step: 30s