services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.systemd'
      - '--collector.processes'
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      resources:
        limits:
          memory: 40M
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true
