services:
  amateurs:
    image: ghcr.io/prgrms-aibe-devcourse/aibe1-finalproject-team01-be:develop
    container_name: amateurs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - amateurs-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: amatuers
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - amateurs-network

networks:
  amateurs-network:

volumes:
  mysql_data:
    driver: local


#  docker-compose -f docker-compose.yml up
