services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: amatuers
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local


#  docker-compose -f docker-compose.yml up
