services:
  app:
    image: ghcr.io/prgrms-aibe-devcourse/aibe1-finalproject-team01-be:latest
    container_name: amateurs-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - amateurs-network

networks:
  amateurs-network:
    external: true
