services:
  app:
    image: ghcr.io/prgrms-aibe-devcourse/aibe1-finalproject-team01-be:latest
    ports:
      - "${STANDBY_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    restart: on-failure:3
    networks:
      - amateurs-network
    volumes:
      - /var/log/spring-boot:/var/log/spring-boot

networks:
  amateurs-network:
    external: true
