services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log/spring-boot:/var/log/spring-boot:ro
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - amateurs-network

networks:
  amateurs-network:
    external: true