global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  - job_name: 'monitoring-server-node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'monitoring-server'
      - source_labels: [__address__]
        target_label: server_type
        replacement: 'monitoring'

  - job_name: 'main-server-node'
    static_configs:
      - targets: ['your-domain.co.kr:9100']
    scheme: https
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'main-server'
      - source_labels: [__address__]
        target_label: server_type
        replacement: 'main'

  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['your-domain.co.kr:443']
    scheme: https
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 20s
    tls_config:
      insecure_skip_verify: false
    relabel_configs:
      - source_labels: [__address__]
        target_label: application
        replacement: 'spring-boot-app'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'production'