services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: amateurs
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - amateurs-network

networks:
  amateurs-network:
    external: true

volumes:
  mysql_data:
    driver: local
