receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true
  
  otlphttp/loki:
    endpoint: http://loki:3100/otlp/v1/logs
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/prometheus, prometheus]
    
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]