name: EC2 배포

on:
  workflow_call:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        type: string
    outputs:
      status:
        description: "배포 실행 결과"
        value: ${{ jobs.summary.outputs.final_status }}
      health_check_status:
        description: "헬스체크 결과"
        value: ${{ jobs.deploy.outputs.health_check_status }}

jobs:
  deploy:
    name: 배포 실행
    uses: ./.github/workflows/deploy-run.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  summary:
    name: 배포 결과
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    outputs:
      final_status: ${{ steps.summary.outputs.final_status }}
      health_check_status: ${{ needs.deploy.outputs.health_check_status }}
    steps:
      - name: 배포 결과 요약
        id: summary
        run: |
          if [[ "${{ needs.deploy.result }}" == "success" ]]; then
            echo "final_status=success" >> $GITHUB_OUTPUT
            echo "Blue-Green 배포가 성공적으로 완료되었습니다"
          else
            echo "final_status=failure" >> $GITHUB_OUTPUT
            echo "Blue-Green 배포 중 오류가 발생했습니다"
          fi
          
          echo "배포 상태: ${{ needs.deploy.outputs.status }}"
          echo "헬스체크 상태: ${{ needs.deploy.outputs.health_check_status }}"