name: 배포 실행

on:
  workflow_call:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        type: string
    outputs:
      status:
        description: "배포 실행 결과"
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    name: EC2 서버 배포
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # Environment 보호 규칙 적용

    outputs:
      status: ${{ steps.set-result.outputs.status }}

    steps:
      - name: EC2 연결 테스트
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ACTIONS_EC2_HOST }}
          username: ${{ secrets.ACTIONS_EC2_USER }}
          key: ${{ secrets.ACTIONS_EC2_SSH_KEY }}
          port: ${{ secrets.ACTIONS_EC2_PORT || 22 }}
          script: |
            echo "EC2 서버 연결 테스트 - Environment: ${{ inputs.environment }}"
            echo "연결 테스트 성공"

      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 배포 스크립트 실행
        id: deploy-script
        uses: appleboy/ssh-action@v1
        env:
          SERVICE_NAME: ${{ inputs.environment }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        with:
          host: ${{ secrets.ACTIONS_EC2_HOST }}
          username: ${{ secrets.ACTIONS_EC2_USER }}
          key: ${{ secrets.ACTIONS_EC2_SSH_KEY }}
          port: ${{ secrets.ACTIONS_EC2_PORT || 22 }}
          script_path: scripts/deploy.sh
          envs: SERVICE_NAME,GITHUB_TOKEN,GITHUB_ACTOR

      - name: 결과 설정
        id: set-result
        if: always()
        run: |
          if [[ "${{ steps.deploy-script.outcome }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo "${{ inputs.environment }} 배포 스크립트가 성공적으로 실행되었습니다"
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "${{ inputs.environment }} 배포 스크립트 실행 중 오류가 발생했습니다"
          fi
